import express from 'express';
import { isauthenicated, login, logout, register, resetPassword, sendResetOtp, sendVerifyOtp, verifyAccount } from '../controller/authController.js';
import userAuth from '../middleware/userAuth.js';
import { AuthenticatedUser } from '../middleware/itemAuthenticatedUser.js';
const authRouter = express.Router();
authRouter.post('/register',register);  
authRouter.post('/login',login);
authRouter.post('/logout',logout);
authRouter.post('/send-verify-otp',AuthenticatedUser,sendVerifyOtp);
authRouter.post('/verifyAccount',AuthenticatedUser,verifyAccount);
authRouter.post('/is-auth',AuthenticatedUser,isauthenicated);
authRouter.post('/send-reset-otp',sendResetOtp);
authRouter.post('/reset-Password',resetPassword);
export default authRouter;